polkadot-js/tools

- CHANGELOG.md
- package.json
- packages/api-cli/package.json
- packages/monitor-rpc/package.json
- yarn.lock
Bump all core `@polkadot/*` dependencies & others
Closes #13
```
$ yarn run:api query.substrate.code --info                                                
yarn run v1.13.0
$ ./packages/api-cli/src/index.js query.substrate.code --info
Wasm code of the runtime.
✨  Done in 3.01s.
```
Closes #14
```
yarn run:api query.balances.freeBalance 5GoKvZWG5ZPYL1WUovuHW3zJBWBP5eT8CbqjdRY4Q6iMaDtZ
yarn run v1.13.0
$ ./packages/api-cli/src/index.js query.balances.freeBalance 5GoKvZWG5ZPYL1WUovuHW3zJBWBP5eT8CbqjdRY4Q6iMaDtZ
{"freeBalance":0}
✨  Done in 4.46s.
```
> Bump dependencies

- CHANGELOG.md
- packages/api-cli/README.md
- packages/api-cli/src/api.ts
Closes #17. Transferring from Alice to Bob -
```
yarn run:api tx.balances.transfer 5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM696e4 12345 --seed "//Alice"
```
> sr25519 support

- .gitignore
- .travis.yml
- package.json
- packages/api-cli/package.json
- packages/monitor-rpc/package.json
- yarn.lock
- common 0.90.1
- api 0.78.1
- latest dev
- bump TS & babel versions
- new cc test reporter (as per other repos)
> Stable common & API

- packages/signer-cli/README.md
- Fix some typos in original document.
- Add paragraph at the end explaining that the user has a limited time to submit the transaction.
> Update signer-cli README with info about mortal extrinsics

- packages/signer-cli/src/cmdSubmit.ts
- packages/signer-cli/src/signer.ts
> Signer: Add option to set mortality as minutes or blocks for the signer-cli tool's submit command

- packages/api-cli/src/api.ts
- packages/signer-cli/src/cmdSign.ts
- packages/signer-cli/src/signer.ts
- params.tmp
> Allow passing tx params in file

- packages/signer-cli/src/cmdSign.ts
> fix(#40): validate payload before signing

- packages/signer-cli/src/cmdSign.ts
#41 
validation here is copy pasta from `apps/page-accounts`.
> fix(#41): validate account seed before signing

- packages/metadata-cmp/src/compare.ts
+ add simple storage count comparison for modules
+ add storage (type) diffing
+ make layouting hierarchical (and improve some other layouting things)
> include storage in metadata comparison

- packages/api-cli/README.md
- packages/api-cli/src/api.ts
Closes https://github.com/polkadot-js/tools/issues/9
> Add --types param to cli

- package.json
- packages/api-cli/package.json
- packages/api-cli/src/api.ts
- packages/json-serve/package.json
- packages/metadata-cmp/package.json
- packages/monitor-rpc/package.json
- packages/signer-cli/package.json
- packages/signer-cli/src/signer.ts
- packages/vanitygen/package.json
- yarn.lock
Closes https://github.com/polkadot-js/tools/issues/207
> Don't parse anything hex into numbers

- package.json
- packages/api-cli/package.json
- packages/api-cli/src/cli.ts
- packages/json-serve/package.json
- packages/metadata-cmp/package.json
- packages/monitor-rpc/package.json
- packages/signer-cli/package.json
- packages/signer-cli/src/signer.ts
- packages/vanitygen/package.json
- yarn.lock
Closes https://github.com/polkadot-js/tools/issues/210
> Fix JSON arguments to api-cli

- package.json
- packages/api-cli/package.json
- packages/api-cli/src/index.cjs
- packages/json-serve/package.json
- packages/json-serve/src/index.cjs
- packages/metadata-cmp/package.json
- packages/metadata-cmp/src/index.cjs
- packages/monitor-rpc/package.json
- packages/monitor-rpc/src/index.cjs
- packages/signer-cli/package.json
- packages/signer-cli/src/index.cjs
- packages/vanitygen/package.json
- packages/vanitygen/src/index.cjs
- yarn.lock
Closes https://github.com/polkadot-js/tools/issues/239 (well, at least works-on-my-computer)
> Fix cjs (dev mode, non-compiled) interactions

- package.json
- packages/api-cli/package.json
- packages/json-serve/package.json
- packages/metadata-cmp/package.json
- packages/metadata-cmp/src/runcli.ts
- packages/monitor-rpc/package.json
- packages/signer-cli/package.json
- packages/vanitygen/package.json
- yarn.lock
Closes https://github.com/polkadot-js/tools/issues/367
As a result of https://github.com/polkadot-js/dev/blob/0571dea97f9abd901afecd9f0f38ea4fec36fbd5/packages/dev/scripts/polkadot-dev-build-ts.mjs#L298
> Workaround for cjs directory includes

- package.json
- packages/metadata-cmp/src/runcli.ts
- yarn.lock
Closes https://github.com/polkadot-js/tools/issues/367
> Fix import path

- docker/build.sh
Simple one liner that will also apply the version tag to docker builds.
Closes #456
> Tag with version as well as latest

- .github/workflows/push-master.yml
Hopefully fixes https://github.com/polkadot-js/tools/actions/runs/4519086822/jobs/7959356583
> Fix docker step with yarn install

- package.json
- packages/api-cli/package.json
- packages/json-serve/package.json
- packages/json-serve/src/runcli.ts
- packages/metadata-cmp/package.json
- packages/monitor-rpc/package.json
- packages/signer-cli/package.json
- yarn.lock
This fixes the internal derives for staking
> Update polkadot/api to 11.0.1

- package.json
- yarn.lock
0.79.3 fixes the standalone package issue
> Bump @polkadot/dev to 0.79.3 w/ topo sort

- package.json
- yarn.lock
Increase test runner performance, and apply some deno build fixes.
> Bump dev to 0.83.2

- package.json
- packages/api-cli/package.json
- packages/json-serve/package.json
- packages/metadata-cmp/package.json
- packages/monitor-rpc/package.json
- packages/signer-cli/package.json
- yarn.lock
This PR aims to upgrade polkadot dependencies.
```
@polkadot/api-augment - 15.8.1
@polkadot/api-derive - 15.8.1
@polkadot/api- 15.8.1
@polkadot/types- 15.8.1
```
> Upgraded @polkadot deps

- package.json
- packages/api-cli/package.json
- packages/json-serve/package.json
- packages/metadata-cmp/package.json
- packages/monitor-rpc/package.json
- packages/signer-cli/package.json
- yarn.lock
This PR aims to upgrade the polkadot dependencies.
```
@polkadot/api-augment ----------------------- ◯ ^15.9.2 ------ ◉ ^15.10.2 -----
@polkadot/api-derive ------------------------ ◯ ^15.9.2 ------ ◉ ^15.10.2 -----
@polkadot/api ------------------------------- ◯ ^15.9.2 ------ ◉ ^15.10.2 -----
@polkadot/types ----------------------------- ◯ ^15.9.2 ------ ◉ ^15.10.2 -----
```
> Upgrade polkadot deps
