packages/api-cli/src/api.ts
This allows complex object for certain api requests to be passed in as JSON.  It will continue to pass primitive values the same way as before.
I tested this against `query.balances.freeBalance` for compatibility and `tx.staking.validate` for handling complex objects and both commands work noq.
Resolves #57
=> Make parser attempt to parse objects to JSON

package.json, yarn.lock
Older version of polkadot api was erroring out against Kusama with:
```
2019-11-08 10:48:59   API/DECORATOR: Error: FATAL: Unable to initialize the API: Unable to find plain type for {"info":6,"type":"AuthorityList"}
at EventEmitter.Init._onProviderConnect (/Users/benfenwick/repos/tools/node_modules/@polkadot/api/base/Init.js:88:23)
at process._tickCallback (internal/process/next_tick.js:68:7)
```
Updating the version of `@polkadot/api` to the most recent version resolves this.
=> Bump the version of @polkadot/api

packages/signer-cli/src/cmdSubmit.ts, yarn.lock
With the import as `import readline from 'readline';` the signer was not waiting for a signature.
=> Fix readline import

packages/signer-cli/README.md, packages/signer-cli/src/cmdSendOffline.ts, packages/signer-cli/src/cmdSubmit.ts, packages/signer-cli/src/signer.ts
This addresses #74 - adds a new `signer-cli` command called `sendOffline` that prints the signed transaction instead of submitting it to the network.
It's basically just a PoC for now. If you find it valuable, I'll work on proper typing and documentation.
=> Signer CLI - send offline

packages/signer-cli/src/cmdSendOffline.ts
Due to some last second refactoring I introduced a bug where the nonce gets lost and always set to 0 when invoking `sendOffline` command. This PR fixes the issue.
=> signer-cli - sendOffline: fixed missing nonce

packages/api-cli/README.md, packages/json-serve/README.md, packages/monitor-rpc/README.md
Both commands will appear to work, but only the latter has the
expected semantics. See https://classic.yarnpkg.com/en/docs/cli/global/.
=> Replace all instances of 'yarn add global' with 'yarn global add'

packages/api-cli/README.md, packages/api-cli/src/api.ts
Suggested in the comments to #100, this enables CLI users to send
transactions which require superuser authentication. Permission-
raising code adapted from https://polkadot.js.org/api/examples/promise/10_upgrade_chain/.
There's a bit of duck-typing added in `makeTx`, largely because it was
very unclear what interfaces are actually appropriate for `signable`
and `auth`. `ApiCallResult` doesn't work for both code branches.
Additionally, casting `fn(...params) as unknown as Proposal` feels
like it may not be the best possible approach, though it's not clear
what a better one would be.
=> Add a --sudo flag to api-cli

CHANGELOG.md, packages/api-cli/README.md, packages/api-cli/src/api.ts
Closes #104.
The leading `@` syntax was chosen because it doesn't conflict with
any standard bash syntax, should be familiar from TS imports, and
should not conflict with any normal operation which a user wants to
do with their transaction. No escapes were therefore implemented.
=> Add magic syntax to api-cli to treat a param as a file and handle it

packages/api-cli/src/api.ts
Encountered an odd bug when using the filename expansion:
```
if (param.startsWith('@')) {
^
TypeError: param.startsWith is not a function
at /usr/local/share/.config/yarn/global/node_modules/@polkadot/api-cli/api.js:93:13
```
Given the type of the variable, that should be impossible:
https://github.com/polkadot-js/tools/blob/2fce4a20407c183edfb249df2a2d496121e938d5/packages/api-cli/src/api.ts#L127
The problem ended up being the yargs middleware which speculatively
parsed JSON in the parameters:
https://github.com/polkadot-js/tools/blob/2fce4a20407c183edfb249df2a2d496121e938d5/packages/api-cli/src/api.ts#L79-L88
This was changing the types of the inputs if something was JSON-parseable,
so the actual type of `params` was `any[]`, not `string[]`. Typescript's type
inference engine …
=> bugfix: handle magic filename expansion before JSON parsing

packages/api-cli/src/api.ts
By default, yargs automatically converts anything that looks like a
number into one while parsing, instead of returning a list of strings.
This not only breaks the magic file middleware, but also produces
unexpected and wrong results when attempting to parse binary blobs,
which are hexadecimal strings prefixed by `0x`.
We don't want this behavior; yargs should just leave the arguments
as strings and let us parse them. This PR adds a configuration
option which disables numeric autoparsing.
---
Before:
```
root@aa304a2389eb:/# polkadot-js-api --ws ws://172.28.1.1:9944 --sudo --seed "//Alice" tx.registrar.registerPara 100 '{"scheduling":"Always"}' 0x123 0x321
param: tx.registrar.registerPara
startsWith: [Function: startsWith]
param: 100
startsWith: undefined
param: {"scheduling":"Always"} …
```
=> Disable yargs behavior to optimistically parse number-seeming arguments

packages/signer-cli/src/RawSigner.ts
This is a small change I did to be able to sign some tx with subkey, this may not be done at the right place, but probably better than the 'bad signature' error.
Reading the code I think this shall also be needed to use with the sign command from this library.
=> hash long payload before display.

packages/api-cli/README.md, packages/api-cli/src/api.ts
Add '--rpc' types support similar with '--types'
Example:
`yarn run:api query.system.account 5FbT2Zh2KBU1VcAw9VRBDDaNMN75J7fLkg8kJk4B6hRqXFSF --types ./types.json --rpc ./rpc.json --ws wss://testnet.pontem.network/ws`
Really helpful for RPC types support.
=> Add RPC types

package.json, packages/api-cli/package.json, packages/json-serve/package.json, packages/metadata-cmp/package.json, packages/metadata-cmp/src/compare.ts, packages/monitor-rpc/package.json, packages/signer-cli/package.json, packages/signer-cli/src/cmdSign.ts, packages/vanitygen/package.json, yarn.lock
Enables https://github.com/paritytech/polkadot/issues/3854
=> Metadata compare update for v14

CHANGELOG.md, package.json, packages/api-cli/src/api.ts, yarn.lock
Makes it clearer as to "why" this happens, e.g. https://github.com/polkadot-js/tools/issues/329#issue-1111114639
Basically it now explicitly indicates that the runtime does not expose the pallet (or method on the pallet)
=> Adjust error messages for not-exposed pallets and methods

packages/api-cli/src/api.ts
Basically the same as #344, but for the `api` tool
=> Support ecdsa signatures in api CLI

docker/Dockerfile.tmpl
Closes https://github.com/polkadot-js/tools/issues/461
For Node.js this is great since it will always pull the latest LTS (which is intended). The previously-used Node 14.x is actually EOL by April 2023. 
For Ubuntu there is no lts concept, so just bump that to latest, non-dev.
=> Use Node LTS on docker (& swap base to latest)

docker/build.sh
Turns out the default is to push only one tag at a time. I'm rusty on my docker apparently.
This will push the second tag.
An alternative is to use `--all-tags`, but that doesn't feel safe to me.
Follow up to: https://github.com/polkadot-js/tools/pull/459
=> Push the version tag to Docker

packages/metadata-cmp/src/runcli.ts
We use the `polkadot-js-metadata-cmp` tool in our CI and it works wonderfully, but we recently started getting type errors with the traceback:
```
TypeError: Cannot read properties of undefined (reading 'undefined')
at <snip>/@polkadot/metadata-cmp/lib/node_modules/@polkadot/metadata-cmp/runcli.js:97:47
at Array.forEach (<anonymous>)
at main (<snip>/@polkadot/metadata-cmp/lib/node_modules/@polkadot/metadata-cmp/runcli.js:82:10)
```
It turns out this was because we removed all of the extrinsics from a pallet. This PR fixes the error by just optionally chaining after we look up the list of extrinsics for a given pallet.
=> metadata-cmp: Properly handle pallets with no extrinsics

packages/api-cli/src/runcli.ts
The logic which determines nonce that is used when signing transaction [is here](https://github.com/polkadot-js/api/blob/fca68ae286bed7098ca5c7d234fadebb626e263e/packages/api-derive/src/tx/signingInfo.ts#L70-L75):
```js
isUndefined(nonce)
? latestNonce(api, address)
: nonce === -1
? nextNonce(api, address)
: of(api.registry.createType('Index', nonce)),
```
So it is:
1) if `nonce` is specified by the caller AND it is not `-1`, then it is used
2) if `nonce` is specified by the caller AND it is `-1`, then it is read from the node using `api.rpc.system.accountNextIndex(_)`, which returns next nonce, taking into account all extrinsics from the pool
3) if `nonce` is not specified by the caller, then it is read from the node using `api.derive.balances.account(_).accountNonce`, which returns next …
=> Added nonce argument to polkadot-js-api

packages/api-cli/src/runcli.ts
Related to https://github.com/paritytech/polkadot-sdk/issues/3176
We use `polkadot-js-api` as part of the bridge integration tests. Lately, since async backing was enabled for test system parachains we are seeing an increasing number of invalid txs in our tests because of https://github.com/paritytech/polkadot-sdk/issues/3204
As a workaround I plan to just disregard these error statuses, but we also need `polkadot-js-api` to gracefully close in this case.
=> [api-cli] Avoid infinite wait on failed txs

packages/metadata-cmp/README.md, packages/metadata-cmp/package.json, packages/metadata-cmp/src/runcli.ts, yarn.lock
Breaking change:
the `metadata-cmp` CLI no longer will use `api.rpc.state.getMetadata` to retrieve metadata. It will always default to using the appropriate runtime calls for the latest version. If one would like to revert to using the legacy rpc call they can use the `--legacy` flag.
=> Set metadata cli to use v15, and add --legacy flag

package.json, packages/api-cli/package.json, packages/json-serve/package.json, packages/metadata-cmp/package.json, packages/monitor-rpc/package.json, packages/signer-cli/package.json, yarn.lock
This PR aims to upgrade polkadot dependencies.
```
@polkadot/api-augment ----------------------- ◯ ^15.8.1 ------ ◉ ^15.9.1
@polkadot/api-derive ------------------------ ◯ ^15.8.1 ------ ◉ ^15.9.1
@polkadot/api ------------------------------- ◯ ^15.8.1 ------ ◉ ^15.9.1
@polkadot/types ----------------------------- ◯ ^15.8.1 ------ ◉ ^15.9.1
```
=> chore: upgraded deps

package.json, packages/api-cli/package.json, packages/json-serve/package.json, packages/metadata-cmp/package.json, packages/monitor-rpc/package.json, packages/signer-cli/package.json, packages/vanitygen/package.json, yarn.lock
This PR aims to upgrade polkadot dependencies.
```
@polkadot/api-augment ----------------------- ◯ ^15.9.1 ------ ◉ ^15.9.2 ------
@polkadot/api-derive ------------------------ ◯ ^15.9.1 ------ ◉ ^15.9.2 ------
@polkadot/api ------------------------------- ◯ ^15.9.1 ------ ◉ ^15.9.2 ------
@polkadot/keyring --------------------------- ◯ ^13.4.3 ------ ◉ ^13.4.4 ------
@polkadot/types ----------------------------- ◯ ^15.9.1 ------ ◉ ^15.9.2 ------
@polkadot/util-crypto ----------------------- ◯ ^13.4.3 ------ ◉ ^13.4.4 ------
@polkadot/util ------------------------------ ◯ ^13.4.3 ------ ◉ ^13.4.4 ------
```
=> chore: upgrade polkadot deps

package.json, packages/api-cli/package.json, packages/json-serve/package.json, packages/metadata-cmp/package.json, packages/monitor-rpc/package.json, packages/signer-cli/package.json, packages/vanitygen/package.json, yarn.lock
This PR aims to upgrade the polkadot dependencies.
```
@polkadot/api-augment ----------------------- ◯ ^15.10.2 -----                  ◉ ^16.0.1 ------
@polkadot/api-derive ------------------------ ◯ ^15.10.2 -----                  ◉ ^16.0.1 ------
@polkadot/api ------------------------------- ◯ ^15.10.2 -----                  ◉ ^16.0.1 ------
@polkadot/keyring --------------------------- ◯ ^13.4.4 ------ ◉ ^13.5.1 ------
@polkadot/types ----------------------------- ◯ ^15.10.2 -----                  ◉ ^16.0.1 ------
@polkadot/util-crypto ----------------------- ◯ ^13.4.4 ------ ◉ ^13.5.1 ------
@polkadot/util ------------------------------ ◯ ^13.4.4 ------ ◉ ^13.5.1 ------
```
=> Upgrade polkadot deps

packages/api-cli/README.md, packages/api-cli/src/runcli.ts
This PR introduces support for passing hex-encoded extrinsic calls directly to the `api-cli` tools.
Previously, crafting complex transactions through the CLI was cumbersome and error-prone, especially for calls involving nested or opaque parameters. In some cases, certain transactions could not be constructed at all via the CLI.
In [Polkadot-JS UI](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.ibp.network%2Fpolkadot#/extrinsics/decode/0x00001074657374), users can generate a hex-encoded representation of an extrinsic. This update allows CLI users to input such hex strings directly, significantly simplifying the process for submitting advanced transactions.
```bash
yarn run:api 
--encodedCall 0x050300fe580ec5fe0e9569d645375acecf5aa19bc0b3188ddd2e2ffc68f6548590d61e0700e8764817 
--seed …
```
=> Submitting hex encoded extrinsic with api-cli

README.md, package.json, packages/api-cli/package.json, packages/json-serve/package.json, packages/metadata-cmp/package.json, packages/monitor-rpc/package.json, packages/signer-cli/package.json, packages/vanitygen/package.json, yarn.lock
This PR aims to upgrade polkadot dependencies.
```
@polkadot/api-augment ----------------------- ◯ ^16.2.2 ------ ◉ ^16.3.1 ------
@polkadot/api-derive ------------------------ ◯ ^16.2.2 ------ ◉ ^16.3.1 ------
@polkadot/api ------------------------------- ◯ ^16.2.2 ------ ◉ ^16.3.1 ------
@polkadot/keyring --------------------------- ◯ ^13.5.2 ------ ◉ ^13.5.3 ------
@polkadot/types ----------------------------- ◯ ^16.2.2 ------ ◉ ^16.3.1 ------
@polkadot/util-crypto ----------------------- ◯ ^13.5.2 ------ ◉ ^13.5.3 ------
@polkadot/util ------------------------------ ◯ ^13.5.2 ------ ◉ ^13.5.3 ------
```
=> Upgrade polkadot dependencies

package.json, packages/api-cli/package.json, packages/json-serve/package.json, packages/metadata-cmp/package.json, packages/monitor-rpc/package.json, packages/signer-cli/package.json, packages/vanitygen/package.json, yarn.lock
This PR aims to update the polkadot-js dependencies.
```
@polkadot/api-augment ----------------------- ◯ ^16.4.1 ------ ◉ ^16.4.3 ------
@polkadot/api-derive ------------------------ ◯ ^16.4.1 ------ ◉ ^16.4.3 ------
@polkadot/api ------------------------------- ◯ ^16.4.1 ------ ◉ ^16.4.3 ------
@polkadot/keyring --------------------------- ◯ ^13.5.3 ------ ◉ ^13.5.4 ------
@polkadot/types ----------------------------- ◯ ^16.4.1 ------ ◉ ^16.4.3 ------
@polkadot/util-crypto ----------------------- ◯ ^13.5.3 ------ ◉ ^13.5.4 ------
@polkadot/util ------------------------------ ◯ ^13.5.3 ------ ◉ ^13.5.4 ------
```
=> Bump polkadot dependencies

package.json, packages/api-cli/package.json, packages/json-serve/package.json, packages/metadata-cmp/package.json, packages/monitor-rpc/package.json, packages/signer-cli/package.json, packages/vanitygen/package.json, yarn.lock
This PR aims to bump polkadot dependencies.
```
@polkadot/api-augment ----------------------- ◯ ^16.4.3 ------ ◉ ^16.4.4 ------
@polkadot/api-derive ------------------------ ◯ ^16.4.3 ------ ◉ ^16.4.4 ------
@polkadot/api ------------------------------- ◯ ^16.4.3 ------ ◉ ^16.4.4 ------
@polkadot/keyring --------------------------- ◯ ^13.5.4 ------ ◉ ^13.5.5 ------
@polkadot/types ----------------------------- ◯ ^16.4.3 ------ ◉ ^16.4.4 ------
@polkadot/util-crypto ----------------------- ◯ ^13.5.4 ------ ◉ ^13.5.5 ------
@polkadot/util ------------------------------ ◯ ^13.5.4 ------ ◉ ^13.5.5 ------
```
=> Bump polkadot deps
